import assert from 'node:assert/strict';
import vm from 'node:vm';
import { readFileSync } from 'node:fs';

const listeners = {};
const element = { addEventListener() {}, classList: { toggle() {}, remove() {} }, querySelectorAll: () => [], focus() {}, innerHTML: '', hidden: true };
const document = { querySelector: () => element, querySelectorAll: () => [], addEventListener: (type, fn) => { listeners[type] = fn; }, body: element };
const context = vm.createContext({ document, structuredClone, console, URL, Intl, Date, Math, setTimeout, clearTimeout, clearInterval, Headers, Request, Response, location: { origin: 'https://app.example', hash: '' }, sessionStorage: { getItem: () => 'sk-test-studio-1234567890' }, localStorage: { getItem: () => null, setItem() {} }, requestAnimationFrame: (fn) => fn(), history: { replaceState() {} } });
const source = readFileSync(new URL('../app/app-v2.js', import.meta.url), 'utf8').replace(/\(async function init\(\)[\s\S]*$/, '');
vm.runInContext(source, context);
vm.runInContext('render = () => {}; saveState = () => {}; showToast = () => {}; checkProviderAuthorization = async () => true;', context);
const run = (code) => vm.runInContext(code, context);

assert.equal(run('plannedTotal()'), 18);
await run("enrichCity('墨尔本')");
assert.equal(run('plannedTotal()'), 24);
assert.equal(run('state.promptGroups[0].options.find((option) => option.id === "dubai").quantity'), 2);
await run("enrichCity('墨尔本')");
assert.equal(run('plannedTotal()'), 24);
assert.equal(run('state.promptGroups[0].options.filter((option) => option.id === "melbourne").length'), 1);
run('state.promptGroups[0].options.forEach((option) => { option.selected = option.id === "melbourne"; });');
assert.equal(run('plannedTotal()'), 6);
assert.match(run('generationPrompt(state.products[3], buildCombinations()[0].tags, buildCombinations()[0].promptDetails)'), /Flinders Street Station/);
run("state.studio.publicPromptId = 'white'");
assert.doesNotMatch(run('generationPrompt(state.products[3], buildCombinations()[0].tags, buildCombinations()[0].promptDetails)'), /Flinders Street Station/);
run("state.studio.publicPromptId = 'cabin'; state.studio.requirements = '后面必须有小木屋'; state.studio.provider = 'qwen'; comparisonRequested = true;");
assert.equal(run('plannedTotal()'), 3);
run('state.ui.confirmBatch = true');
assert.match(run('renderConfirmDialog()'), /Wan 2.6 Image/);
assert.doesNotMatch(run('renderConfirmDialog()'), /TENT-2P-014/);
assert.match(run('renderConfirmDialog()'), /预览首张图的实际提示词/);
assert.match(run('renderConfirmDialog()'), /<details class="generation-summary" open>/);
run("promptReview.entries[0].prompt += '\\n后面必须有小木屋，检验手动修改';");
const creditsBeforeConfirmation = run('state.credits');
run('confirmCurrentPromptReview()');
assert.equal(run('state.credits'), creditsBeforeConfirmation);
assert.equal(run('state.ui.confirmBatch'), false);
assert.equal(run('hasConfirmedPromptReview(true)'), true);
assert.equal(run('hasConfirmedPromptReview(false)'), false);
assert.equal(run('state.batch.results.length'), 0);
run('comparisonRequested = true;');
run('submitQwenBatch = async (results) => { state.studio.requirements = "中途改变的要求"; results.forEach((item) => { item.status = "ready"; item.image = "data:image/jpeg;base64,aW1hZ2U="; }); }; pollQwenBatch = async () => { activeGenerationId = ""; state.batch.status = "ready"; };');
await run('startBatchGeneration()');
assert.equal(run('state.batch.results.length'), 3);
assert.equal(run('new Set(state.batch.results.map((item) => item.prompt)).size'), 1);
assert.match(run('state.batch.results[0].prompt'), /后面必须有小木屋/);
assert.doesNotMatch(run('state.batch.results[0].prompt'), /中途改变的要求/);
assert.equal(run('new Set(state.batch.results.map((item) => item.model)).size'), 3);
run('state.studio.selectedProductIds = [];');
assert.match(run('renderResultGroups()'), /result-preview-trigger/);
assert.match(run('renderResultGroups()'), /TENT-3P-001/);
run('saveBatch()');
assert.equal(run('state.savedAssets[0].prompt'), run('state.batch.results[0].prompt'));
assert.equal(run('state.savedAssets[0].demo'), false);

run("state.studio.selectedProductIds = ['p-4']; comparisonRequested = false;");
run('preparePromptReview(); confirmCurrentPromptReview();');
await run('startBatchGeneration()');
assert.equal(run('state.batchHistory.length'), 1);
assert.equal(run('state.batchHistory[0].results.length'), 3);
run('state.batch.status = "generating"; state.batch.results = [{status: "loading", taskId: "", productId: "p-4", tags: []}];');
await run('resumePendingBatch()');
assert.equal(run('state.batch.results[0].status'), 'failed');
assert.match(run('state.batch.results[0].error'), /可能已计费/);

run('state = structuredClone(seedState); state.schemaVersion = 7; state.studio.generationMode = "fast"; applySavedState(structuredClone(state));');
assert.equal(run('state.schemaVersion'), 8);
assert.equal(run('state.studio.generationMode'), 'fast');
assert.equal(run('state.savedAssets.every((asset) => asset.demo)'), true);
assert.equal(run('state.promptGroups[0].options.some((option) => option.id === "melbourne")'), true);
run("state.publicPrompts.push({id: 'white-copy', backgroundMode: 'none', prompt: '纯白背景'}); state.studio.publicPromptId = 'white-copy';");
assert.doesNotMatch(run('generationPrompt(state.products[3], ["当地背景：墨尔本天际线"], [])'), /墨尔本天际线/);
run("regionPreviewId = ''; state.ui.promptDialogGroupId = 'group-location'; state.promptGroups[0].options.find((option) => option.id === 'melbourne').selected = true;");
assert.match(run('renderPromptDialog()'), /添加并补全背景/);
assert.match(run('renderPromptDialog()'), /data-region-prompt/);
assert.doesNotMatch(run('renderStudio()'), /id="city-name"/);
assert.doesNotMatch(run('renderStudio()'), /AI 地域背景助手/);
await run("enrichCity('')");
assert.match(run('cityPlannerError'), /请输入/);
run('apiJson = async () => { throw new Error("测试网络错误"); };');
await run("enrichCity('日本·京都')");
assert.equal(run('cityDraft'), '日本·京都');
assert.match(run('renderPromptDialog()'), /测试网络错误/);
run('apiJson = async () => ({prompt: "京都木质町屋与庭院景观"});');
await run("enrichCity('日本·京都')");
assert.equal(run('state.promptGroups[0].options.filter((option) => option.label === "日本·京都").length'), 1);
assert.equal(run('state.promptGroups[0].options.find((option) => option.id === "melbourne").selected'), true);
assert.equal(run('cityDraft'), '');
assert.match(run('renderPromptDialog()'), /京都木质町屋/);
assert.match(run('renderPromptDialog()'), /确认地区提示词/);
const compactStudio = run('renderStudio()');
assert.ok(compactStudio.indexOf('id="studio-provider"') < compactStudio.indexOf('选择参考产品图'));
assert.doesNotMatch(run('renderStudio()'), /id="universal-prompt"|provider-option-grid/);
assert.match(run('generationPrompt(state.products[3], [], [])'), /真实商业摄影质感/);
listeners.change({target: {id: 'studio-provider', value: 'qwen'}});
listeners.change({target: {id: 'studio-quality', value: 'wan'}});
assert.equal(run('state.studio.model'), 'wan2.6-image');
listeners.change({target: {id: 'studio-provider', value: 'openai'}});
assert.equal(run('state.studio.generationMode'), 'quality');
listeners.change({target: {id: 'studio-quality', value: 'fast'}});
assert.equal(run('state.studio.model'), run('PROVIDERS.openai.profiles.fast.code'));
run("state.batch.status = 'generating';");
listeners.change({target: {id: 'studio-provider', value: 'qwen'}});
listeners.change({target: {id: 'studio-quality', value: 'quality'}});
assert.equal(run('state.studio.provider'), 'openai');
assert.equal(run('state.studio.generationMode'), 'fast');
assert.equal((run('renderStudioSettings(true)').match(/disabled/g) || []).length, 2);
run("state.batch.status = 'ready'; state.studio.publicPromptId = 'brief'; comparisonRequested = false; regionPreviewId = ''; preparePromptReview(); state.ui.confirmBatch = true;");
const simplifiedStudio = run('renderStudio()');
assert.doesNotMatch(simplifiedStudio, /id="design-requirements"|公共提示词区|预览首张图的实际提示词/);
assert.ok(simplifiedStudio.indexOf('公共提示词模板') > simplifiedStudio.indexOf('选择提示词组合'));
assert.ok(simplifiedStudio.indexOf('公共提示词模板') < simplifiedStudio.indexOf('class="prompt-group-list"'));
assert.match(run('promptReview.entries[0].prompt'), /Flinders Street Station/);
assert.doesNotMatch(run('generationPrompt(state.products[3], [], [])'), /必须落实的补充要求/);
const clickAction = async (action) => { const button = {dataset: {action}}; await listeners.click({target: {closest: (selector) => selector === '[data-action]' ? button : null}}); };
await clickAction('edit-reviewed-prompt');
assert.equal(run('promptReviewEditing'), true);
listeners.input({target: {id:'final-prompt-text',value:' ' ,dataset:{}}});
await clickAction('save-reviewed-prompt');
assert.equal(run('promptReviewEditing'), true);
assert.match(run('promptReviewError'), /请输入/);
listeners.input({target: {id:'final-prompt-text',value:'修改后的墨尔本地标与帐篷配方',dataset:{}}});
await clickAction('save-reviewed-prompt');
assert.equal(run('promptReviewEditing'), false);
assert.equal(run('reviewedPrompt(selectedProducts()[0], buildCombinations()[0], 0)'), '修改后的墨尔本地标与帐篷配方');
assert.notEqual(run('reviewedPrompt(selectedProducts()[0], buildCombinations()[1], 1)'), '修改后的墨尔本地标与帐篷配方');
run("state.studio.publicPromptId = 'white';");
assert.notEqual(run('reviewedPrompt(selectedProducts()[0], buildCombinations()[0], 0)'), '修改后的墨尔本地标与帐篷配方');
assert.doesNotMatch(run('renderConfirmDialog()'), /Flinders Street Station/);
run("state.studio.provider = 'qwen'; state.studio.generationMode = 'wan'; preparePromptReview(); promptReview.entries[0].prompt = '长'.repeat(2001);");
const creditsBeforeInvalidPrompt = run('state.credits');
run('confirmCurrentPromptReview()');
assert.equal(run('state.credits'), creditsBeforeInvalidPrompt);
assert.equal(run('promptReviewEditing'), true);
assert.match(run('promptReviewError'), /2000.*尚未提交或扣分/);
run("state = structuredClone(seedState); comparisonRequested = false; promptReview = null;");
const inlineComparison = run('renderComparisonSection(false)');
assert.match(inlineComparison, /小样模型对比/);
assert.match(inlineComparison, /GPT Image 2\.5/);
assert.match(inlineComparison, /Low 质量/);
assert.match(inlineComparison, /High 质量/);
assert.match(inlineComparison, /2 张对比图 · 6 积分/);
assert.match(inlineComparison, /悉尼歌剧院/);
assert.match(inlineComparison, /对比共用提示词/);
assert.doesNotMatch(inlineComparison, /<details|TENT-2P-014/);
assert.equal(run('comparisonRequested'), false);
assert.equal(run('plannedTotal()'), 18);
run("state.studio.provider = 'qwen';");
assert.match(run('renderComparisonSection(false)'), /3 张对比图 · 9 积分/);
assert.match(run('renderComparisonSection(false)'), /Wan 2\.6 Image/);
assert.doesNotMatch(run('renderComparisonSection(true)'), /data-action="review-comparison"/);
run('state.studio.selectedProductIds = [];');
assert.match(run('renderComparisonSection(false)'), /先选择参考产品/);
assert.doesNotMatch(run('renderComparisonSection(false)'), /data-action="review-comparison"/);
run('state = structuredClone(seedState); comparisonRequested = false; promptReviewEditing = false; confirmedPromptReviews = {batch: null, comparison: null}; activeGenerationId = "";');
const unconfirmedCredits = run('state.credits');
await run('startBatchGeneration()');
assert.equal(run('state.credits'), unconfirmedCredits);
assert.equal(run('state.batch.results.length'), 0);
assert.match(run('renderStudio()'), /data-action="generate-batch" disabled/);
assert.doesNotMatch(run('renderComparisonSection(false)'), /data-action="generate-comparison"/);
run('preparePromptReview(); state.ui.confirmBatch = true;');
assert.match(run('renderConfirmDialog()'), /data-action="confirm-prompts"/);
assert.doesNotMatch(run('renderConfirmDialog()'), /data-action="confirm-batch"|开始生成/);
run('promptReview.entries[0].prompt = "确认过的精修儿童帐篷摄影提示词";');
await clickAction('confirm-prompts');
assert.equal(run('hasConfirmedPromptReview(false)'), true);
assert.equal(run('state.credits'), unconfirmedCredits);
assert.equal(run('state.ui.confirmBatch'), false);
assert.match(run('renderStudio()'), /data-action="generate-batch" >/);
assert.doesNotMatch(run('renderComparisonSection(false)'), /data-action="generate-comparison"/);
run('preparePromptReview();');
assert.equal(run('promptReview.entries[0].prompt'), '确认过的精修儿童帐篷摄影提示词');
await clickAction('edit-reviewed-prompt');
assert.equal(run('hasConfirmedPromptReview(false)'), false);
await clickAction('cancel-reviewed-prompt');
await clickAction('confirm-prompts');
for (const mutation of [
  'state.studio.ratio = "1:1";',
  'state.studio.generationMode = "fast";',
  'state.studio.publicPromptId = "white";',
  'state.promptGroups[0].options.find((option) => option.selected).quantity += 1;',
  'state.studio.selectedProductIds = ["p-4"];',
  'state.products[0].name += "修改";'
]) {
  run('state = structuredClone(seedState); comparisonRequested = false; preparePromptReview(); confirmCurrentPromptReview();');
  assert.equal(run('hasConfirmedPromptReview(false)'), true);
  run(mutation);
  assert.equal(run('hasConfirmedPromptReview(false)'), false, mutation);
}
run('state = structuredClone(seedState); preparePromptReview(); confirmCurrentPromptReview(); checkProviderAuthorization = async () => { state.studio.ratio = "1:1"; return true; };');
const creditsBeforeAuthorizationChange = run('state.credits');
await run('startBatchGeneration()');
assert.equal(run('state.credits'), creditsBeforeAuthorizationChange);
assert.equal(run('state.batch.results.length'), 0);
run('checkProviderAuthorization = async () => true; preparePromptReview(); promptReview.entries[0].prompt = "最终确认版本"; confirmCurrentPromptReview(); submitOpenAiBatch = async (results) => { results.forEach((item) => { item.status = "ready"; }); activeGenerationId = ""; state.batch.status = "ready"; };');
await clickAction('generate-batch');
assert.equal(run('state.batch.results.length'), 18);
assert.equal(run('state.batch.results[0].prompt'), '最终确认版本');
assert.equal(run('state.credits'), creditsBeforeAuthorizationChange - 54);
assert.equal(run('hasConfirmedPromptReview(false)'), false);
run('state = structuredClone(seedState); studioComparisonMode = false; comparisonRequested = false; confirmedPromptReviews = {batch: null, comparison: null};');
assert.equal((run('renderStudio()').match(/class="generation-controls"/g) || []).length, 1);
assert.match(run('renderStudio()'), /id="studio-generation-type"/);
assert.doesNotMatch(run('renderStudio()'), /data-action="review-comparison"/);
listeners.change({target: {id: 'studio-generation-type', value: 'comparison'}});
assert.equal(run('studioComparisonMode'), true);
assert.equal(run('plannedTotal()'), 2);
assert.match(run('formulaText()'), /2 张对比图/);
assert.match(run('renderStudio()'), /data-action="generate-comparison" disabled/);
assert.doesNotMatch(run('renderStudio()'), /data-action="generate-batch"/);
run('comparisonRequested = true; preparePromptReview(); confirmCurrentPromptReview();');
assert.equal(run('studioComparisonMode'), true);
assert.equal(run('comparisonRequested'), false);
assert.equal(run('plannedTotal()'), 2);
assert.match(run('renderStudio()'), /data-action="generate-comparison" >/);
listeners.change({target: {id: 'studio-generation-type', value: 'batch'}});
assert.equal(run('plannedTotal()'), 18);
assert.match(run('renderStudio()'), /data-action="generate-batch" disabled/);
listeners.change({target: {id: 'studio-generation-type', value: 'comparison'}});
await clickAction('generate-comparison');
assert.equal(run('state.batch.results.length'), 2);
assert.equal(run('state.batch.comparison'), true);
assert.equal(run('state.credits'), run('seedState.credits') - 6);
console.log('Studio prompt confirmation gates, comparison, batch snapshots, history, migration and recovery tests passed.');
