import assert from 'node:assert/strict';
import vm from 'node:vm';
import { readFileSync } from 'node:fs';

const listeners = {};
const element = { addEventListener() {}, classList: { toggle() {}, remove() {} }, querySelectorAll: () => [], focus() {}, innerHTML: '', hidden: true };
const document = { querySelector: () => element, querySelectorAll: () => [], addEventListener: (type, fn) => { listeners[type] = fn; }, body: element };
const context = vm.createContext({ document, structuredClone, console, URL, Intl, Date, Math, setTimeout, clearTimeout, clearInterval, Headers, Request, Response, location: { origin: 'https://app.example', hash: '' }, sessionStorage: { getItem: (key) => key.includes('google-maps') ? 'AIzaTestGoogleMapsGroundingLiteKey123456' : 'sk-test-studio-1234567890', setItem() {}, removeItem() {} }, localStorage: { getItem: () => null, setItem() {} }, requestAnimationFrame: (fn) => fn(), history: { replaceState() {} } });
vm.runInContext(readFileSync(new URL('../app/core.js', import.meta.url), 'utf8'), context);
const source = readFileSync(new URL('../app/app-v2.js', import.meta.url), 'utf8').replace(/\(async function init\(\)[\s\S]*$/, '');
vm.runInContext(source, context);
vm.runInContext('render = () => {}; saveState = () => {}; showToast = () => {}; checkProviderAuthorization = async () => true;', context);
const run = (code) => vm.runInContext(code, context);
run('const productionPollQwenBatch = pollQwenBatch; const productionFinishBatch = finishBatch; const productionSleep = sleep; const productionApiJson = apiJson; const productionGroundLocationOptions = groundLocationOptions; const productionLocationGroundingIsFresh = locationGroundingIsFresh;');
run(`for (const target of [seedState, state]) {
  const locationGroup = target.promptGroups.find((group) => group.id === 'group-location');
  locationGroup.options.forEach((option) => {
    option.sceneGrounding = {summary: option.label + ' 地图检索摘要', sources: [{title: option.label + ' · Google Maps', url: 'https://www.google.com/maps/place/' + option.id, placeId: option.id}], resolvedAt: '2026-09-16T00:00:00.000Z', expiresAt: '2099-10-16T00:00:00.000Z', requestFingerprint: locationSearchFingerprint(option)};
  });
}`);

assert.equal(run('plannedTotal()'), 18);
await run("enrichCity('墨尔本')");
assert.equal(run('plannedTotal()'), 24);
assert.equal(run('state.promptGroups[0].options.find((option) => option.id === "dubai").quantity'), 2);
await run("enrichCity('墨尔本')");
assert.equal(run('plannedTotal()'), 24);
assert.equal(run('state.promptGroups[0].options.filter((option) => option.id === "melbourne").length'), 1);
run('state.promptGroups[0].options.forEach((option) => { option.selected = option.id === "melbourne"; });');
run(`{ const option = state.promptGroups[0].options.find((item) => item.id === 'melbourne'); option.sceneGrounding = {summary: '墨尔本雅拉河水岸、弗林德斯街车站与 CBD 的 Google Maps 检索结果。', sources: [{title: 'Flinders Street Station · Google Maps', url: 'https://www.google.com/maps/place/flinders-street-station', placeId: 'melbourne'}], resolvedAt: '2026-09-16T01:00:00.000Z', expiresAt: '2099-10-16T00:00:00.000Z', requestFingerprint: locationSearchFingerprint(option)}; }`);
assert.equal(run('plannedTotal()'), 6);
const melbournePrompt = run('generationPrompt(state.products[3], buildCombinations()[0].tags, buildCombinations()[0].promptDetails)');
assert.match(melbournePrompt, /【地域场景硬约束｜不可省略】/);
assert.match(melbournePrompt, /Google Maps Grounding Lite/);
assert.match(melbournePrompt, /Google Maps 检索依据/);
assert.match(melbournePrompt, /墨尔本雅拉河水岸/);
assert.equal(run('buildCombinations()[0].sceneGroundingId'), 'melbourne');
assert.equal(run('buildCombinations()[0].sceneGroundingReady'), true);
assert.match(run("googleMapsSearchUrl(state.promptGroups[0].options.find((option) => option.id === 'melbourne'))"), /^https:\/\/www\.google\.com\/maps\/(?:place|search)/);
run("delete state.promptGroups[0].options.find((option) => option.id === 'melbourne').sceneGrounding; comparisonRequested = false; confirmedPromptReviews = {batch: null, comparison: null}; preparePromptReview();");
await run("groundLocationOptions = async () => false; confirmCurrentPromptReview(true);");
assert.equal(run('hasConfirmedPromptReview(false)'), false);
assert.equal(run('selectedLocationsMissingEvidence().length'), 1);
run("{ const option = state.promptGroups[0].options.find((item) => item.id === 'melbourne'); option.sceneGrounding = {summary: '墨尔本雅拉河水岸、弗林德斯街车站与 CBD 的 Google Maps 检索结果。', sources: [{title: 'Flinders Street Station · Google Maps', url: 'https://www.google.com/maps/place/flinders-street-station', placeId: 'melbourne'}], resolvedAt: '2026-09-16T01:00:00.000Z', expiresAt: '2099-10-16T00:00:00.000Z', requestFingerprint: locationSearchFingerprint(option)}; state.ui.promptDialogGroupId = ''; promptReview = null; promptReviewError = ''; } ");
run('groundLocationOptions = productionGroundLocationOptions;');
run("locationGroundingIsFresh = (option) => Boolean(option?.sceneGrounding?.summary && option?.sceneGrounding?.sources?.length && new Date(option.sceneGrounding.expiresAt || 0).getTime() > Date.now());");
assert.match(melbournePrompt, /Flinders Street Station/);
assert.match(melbournePrompt, /背景环境占画面 40%–55%/);
assert.match(melbournePrompt, /主地域锚点，占画面约 8%–18%/);
assert.match(melbournePrompt, /同一台相机、同一地面和同一个透视系统/);
assert.match(melbournePrompt, /人物数量硬约束｜0人/);
assert.match(melbournePrompt, /必须严格等于 0/);
assert.doesNotMatch(run("buildCombinations()[0].promptDetails.join(' ')"), /改变人物动作|人物站位|儿童互动动作/);
assert.match(melbournePrompt, /帐篷按标称尺寸“120 × 120 × 150 cm”/);
assert.ok(melbournePrompt.length < 6000);
assert.ok(melbournePrompt.indexOf('【地域场景硬约束｜不可省略】') < melbournePrompt.indexOf('场景任务：'));
assert.equal((melbournePrompt.match(/目标地域：/g) || []).length, 1);
run("state.studio.publicPromptId = 'white'");
const whitePromptWithoutLocation = run('generationPrompt(state.products[3], buildCombinations()[0].tags, buildCombinations()[0].promptDetails)');
assert.doesNotMatch(whitePromptWithoutLocation, /Flinders Street Station|地域场景硬约束/);
assert.match(whitePromptWithoutLocation, /人物数量硬约束｜0人/);
assert.match(whitePromptWithoutLocation, /不得出现任何场景道具/);
run("state.studio.publicPromptId = 'family'");
const familyWithoutPeople = run('generationPrompt(state.products[3], buildCombinations()[0].tags, buildCombinations()[0].promptDetails)');
assert.match(familyWithoutPeople, /人物数量硬约束｜0人/);
assert.doesNotMatch(familyWithoutPeople, /人物数量硬约束｜1人/);
run("state.studio.otherRequirements = '请安排两个孩子玩耍';");
assert.match(run('generationPrompt(state.products[3], buildCombinations()[0].tags, buildCombinations()[0].promptDetails)'), /人物数量硬约束｜0人/);
run("state.studio.otherRequirements = ''; const peopleGroup = state.promptGroups.find((group) => group.id === 'group-people'); peopleGroup.options.forEach((option) => { option.selected = option.id === 'people-one'; });");
const familyPrompt = run('generationPrompt(state.products[3], buildCombinations()[0].tags, buildCombinations()[0].promptDetails)');
assert.match(familyPrompt, /人物数量硬约束｜1人/);
assert.match(familyPrompt, /本张只允许 1 名儿童/);
assert.match(familyPrompt, /人物总数必须严格等于 1/);
assert.match(familyPrompt, /所有人的完整五官和互动处在清晰焦平面/);
assert.match(familyPrompt, /人物互动硬约束｜每个人都必须可见/);
assert.match(familyPrompt, /身体一半在篷内、一半在篷外/);
assert.match(familyPrompt, /一只手明确轻扶软质门帘边缘/);
assert.match(familyPrompt, /只在旁边摆拍/);
run("state.promptGroups.find((group) => group.id === 'group-people').options.forEach((option) => { option.selected = option.id === 'people-two'; });");
const twoPeoplePrompt = run('generationPrompt(state.products[3], buildCombinations()[0].tags, buildCombinations()[0].promptDetails)');
assert.match(twoPeoplePrompt, /人物数量硬约束｜2人/);
assert.match(twoPeoplePrompt, /人物总数必须严格等于 2/);
assert.match(twoPeoplePrompt, /儿童 A/);
assert.match(twoPeoplePrompt, /儿童 B/);
assert.match(twoPeoplePrompt, /共同形成正在使用帐篷的关系/);
run("state.promptGroups.find((group) => group.id === 'group-people').options.forEach((option) => { option.selected = option.id === 'people-three'; });");
const threePeoplePrompt = run('generationPrompt(state.products[3], buildCombinations()[0].tags, buildCombinations()[0].promptDetails)');
assert.match(threePeoplePrompt, /人物数量硬约束｜3人/);
assert.match(threePeoplePrompt, /儿童 C/);
run("state.promptGroups.find((group) => group.id === 'group-people').options.forEach((option) => { option.selected = option.id === 'people-one'; });");
run("state.studio.publicPromptId = 'cabin'; state.studio.requirements = '后面必须有小木屋'; state.studio.provider = 'qwen'; comparisonRequested = true;");
run("state.promptGroups.find((group) => group.id === 'group-location').options.filter((option) => option.selected).forEach((option) => { option.sceneGrounding.requestFingerprint = locationSearchFingerprint(option); });");
assert.equal(run('plannedTotal()'), 3);
run('state.ui.confirmBatch = true');
assert.match(run('renderConfirmDialog()'), /Wan 2.6 Image/);
assert.doesNotMatch(run('renderConfirmDialog()'), /TENT-2P-014/);
assert.match(run('renderConfirmDialog()'), /预览首张图的实际提示词/);
assert.match(run('renderConfirmDialog()'), /<details class="generation-summary" open>/);
run("promptReview.entries[0].prompt += '\\n后面必须有小木屋，检验手动修改';");
const creditsBeforeConfirmation = run('state.credits');
assert.equal(run('promptReview.fingerprint'), run('reviewFingerprint()'));
assert.ok(run('promptReview.entries[0].prompt.length') <= 2000, run('promptReview.entries[0].prompt.length'));
run('confirmCurrentPromptReview()');
assert.equal(run('state.credits'), creditsBeforeConfirmation);
assert.equal(run('state.ui.confirmBatch'), false);
assert.equal(run('hasConfirmedPromptReview(true)'), true);
assert.equal(run('hasConfirmedPromptReview(false)'), false);
assert.equal(run('state.batch.results.length'), 0);
run('comparisonRequested = true;');
run('submitQwenBatch = async (results) => { state.studio.requirements = "中途改变的要求"; results.forEach((item) => { item.status = "ready"; item.image = "data:image/jpeg;base64,aW1hZ2U="; }); }; pollQwenBatch = async () => { activeGenerationId = ""; state.batch.status = "ready"; };');
await run('startBatchGeneration()');
assert.equal(run('state.batch.results.length'), 3);
assert.equal(run('new Set(state.batch.results.map((item) => item.prompt)).size'), 1);
assert.match(run('state.batch.results[0].prompt'), /后面必须有小木屋/);
assert.doesNotMatch(run('state.batch.results[0].prompt'), /中途改变的要求/);
assert.equal(run('new Set(state.batch.results.map((item) => item.model)).size'), 3);
run('state.studio.selectedProductIds = [];');
assert.match(run('renderResultGroups()'), /result-preview-trigger/);
assert.match(run('renderResultGroups()'), /TENT-3P-001/);
run('state.ui.batchAuditOpen = false;');
assert.match(run('renderBatchTools()'), /id="batch-audit-details"/);
assert.doesNotMatch(run('renderBatchTools()'), /id="batch-audit-details" open/);
assert.match(run('renderResultSummaryStrip()'), /3[\s\S]*完成[\s\S]*0[\s\S]*已验收/);
run('state.ui.batchAuditOpen = true;');
assert.match(run('renderBatchTools()'), /id="batch-audit-details" open/);
run('state.ui.batchAuditOpen = false;');
run("state.batch.results.forEach((item) => { item.evaluation = {structure: 5, location: 'pass', shot: 'pass', people: 'pass', defects: 'pass', deliverable: 'pass'}; item.review = Core.deriveReview(item.evaluation); });");
run('saveBatch()');
assert.equal(run('state.savedAssets[0].prompt'), run('state.batch.results[0].prompt'));
assert.equal(run('state.savedAssets[0].demo'), false);

run("state.studio.selectedProductIds = ['p-4']; comparisonRequested = false;");
run('preparePromptReview(); confirmCurrentPromptReview();');
await run('startBatchGeneration()');
assert.equal(run('state.batchHistory.length'), 1);
assert.equal(run('state.batchHistory[0].results.length'), 3);
assert.ok(run('renderStudio().indexOf("id=\\"batch-history\\"")') < run('renderStudio().indexOf("<aside class=\\"run-panel\\"")'));
run('state.batch.status = "generating"; state.batch.results = [{status: "loading", taskId: "", productId: "p-4", tags: []}];');
await run('resumePendingBatch()');
assert.equal(run('state.batch.results[0].status'), 'failed');
assert.match(run('state.batch.results[0].error'), /可能已计费/);

run(`state = structuredClone(seedState);
  state.savedAssets = [];
  state.batch = {id: 'B-POLL-RETRY', status: 'generating', provider: 'qwen', generationMode: 'quality', submissionComplete: true, nextSubmissionAt: 0, results: [{
    id: 'result-poll-retry', productId: 'p-1', productSnapshot: structuredClone(state.products[0]), image: '', tags: ['当地背景：悉尼'], prompt: '测试自动查询与归档', provider: 'qwen', generationMode: 'quality', model: 'qwen-image-3.0-pro', evaluation: Core.emptyEvaluation(), review: 'pending', status: 'loading', taskId: 'task-poll-retry', submittedAt: Date.now(), remoteStatus: 'RUNNING', error: '', saved: false, creditRefunded: false
  }]};
  activeGenerationId = state.batch.id;
  let transientPollAttempts = 0;
  sleep = async () => {};
  apiJson = async () => {
    transientPollAttempts += 1;
    if (transientPollAttempts === 1) { const error = new Error('临时网络抖动'); error.code = 'NETWORK_ERROR'; throw error; }
    return {taskStatus: 'SUCCEEDED', imageUrls: ['https://example.com/generated.jpg']};
  };`);
await run("productionPollQwenBatch('B-POLL-RETRY')");
assert.equal(run('transientPollAttempts'), 2);
assert.equal(run('state.batch.status'), 'ready');
assert.equal(run('state.batch.results[0].status'), 'ready');
assert.equal(run('state.batch.results[0].creditRefunded'), false);
assert.equal(run('state.savedAssets.length'), 1);
assert.equal(run('state.savedAssets[0].sourceResultId'), 'result-poll-retry');
assert.equal(run('state.savedAssets[0].review'), 'pending');
assert.match(run('state.savedAssets[0].tags.join(" ")'), /待验收/);
run("state.batch.results[0].evaluation = {structure: 5, location: 'pass', shot: 'pass', people: 'pass', defects: 'pass', deliverable: 'pass'}; state.batch.results[0].review = Core.deriveReview(state.batch.results[0].evaluation); syncResultAsset(state.batch.results[0]);");
assert.equal(run('state.savedAssets.length'), 1);
assert.equal(run('state.savedAssets[0].review'), 'pass');
assert.match(run('state.savedAssets[0].tags.join(" ")'), /验收通过/);

run(`state = structuredClone(seedState); state.savedAssets = [];
  state.batch = {id: 'B-AUTO-QA', status: 'generating', provider: 'qwen', generationMode: 'quality', results: [{
    id: 'result-auto-qa', productId: 'p-1', image: '', tags: [], prompt: '【人物数量硬约束｜1人】\\n【人物互动硬约束｜每个人都必须可见】', ratio: '4:3', generationMode: 'quality', model: 'qwen-image-3.0-pro', status: 'loading', taskId: 'task-original', remoteStatus: 'SUCCEEDED', autoRepairAttempts: 0, creditRefunded: false, evaluation: Core.emptyEvaluation(), review: 'pending'
  }]};
  let autoQaCalls = 0;
  apiJson = async (path, options) => {
    if (path === '/api/qwen/inspect-image') {
      autoQaCalls += 1;
      return autoQaCalls === 1
        ? {pass:false, personCount:2, childCount:2, interactionVisible:false, issues:['出现第二名儿童','人物没有接触帐篷']}
        : {pass:true, personCount:1, childCount:1, atTentEntrance:true, touchingTent:true, interactionVisible:true, allPeopleInteracting:true, extraPersonVisible:false, issues:[]};
    }
    if (path === '/api/qwen/generate') {
      const body = JSON.parse(options.body);
      if (!body.repairImageUrl || !body.prompt.includes('先删除输入图片中的全部现有人物')) throw new Error('修复请求缺少目标图片或硬约束');
      return {taskId:'task-repair', model:'qwen-image-3.0-pro'};
    }
    throw new Error('unexpected path');
  };`);
await run("verifyOrRepairQwenResult(state.batch.results[0], 'https://example.com/first.jpg')");
assert.equal(run('state.batch.results[0].status'), 'loading');
assert.equal(run('state.batch.results[0].taskId'), 'task-repair');
assert.equal(run('state.batch.results[0].autoRepairAttempts'), 1);
assert.equal(run('state.savedAssets.length'), 0);
assert.match(run('renderResultGroups()'), /人物未达标 · 自动修复中/);
await run("verifyOrRepairQwenResult(state.batch.results[0], 'https://example.com/repaired.jpg')");
assert.equal(run('state.batch.results[0].status'), 'ready');
assert.equal(run('state.batch.results[0].image'), 'https://example.com/repaired.jpg');
assert.match(run('state.batch.results[0].tags.join(" ")'), /人物自动验收通过/);
assert.match(run('state.batch.results[0].tags.join(" ")'), /自动修复 1 次/);
assert.equal(run('state.savedAssets.length'), 1);
run(`state.savedAssets = []; state.credits = 10; state.batch.results[0] = {
  id: 'result-auto-qa-fail', productId: 'p-1', image: '', tags: [], prompt: '【人物数量硬约束｜1人】', ratio: '4:3', generationMode: 'quality', status: 'loading', taskId: 'task-repair-failed', remoteStatus: 'SUCCEEDED', autoRepairAttempts: 1, creditRefunded: false, evaluation: Core.emptyEvaluation(), review: 'pending'
}; apiJson = async (path) => path === '/api/qwen/inspect-image' ? {pass:false, personCount:2, childCount:2, interactionVisible:false, issues:['仍然出现两个人']} : Promise.reject(new Error('unexpected path'));`);
await run("verifyOrRepairQwenResult(state.batch.results[0], 'https://example.com/still-bad.jpg')");
assert.equal(run('state.batch.results[0].status'), 'failed');
assert.equal(run('state.batch.results[0].image'), '');
assert.equal(run('state.savedAssets.length'), 0);
assert.equal(run('state.credits'), 13);
assert.match(run('state.batch.results[0].error'), /未进入素材库/);

run(`state = structuredClone(seedState); state.credits = 100; state.batch = {id: 'B-STOP', status: 'generating', provider: 'qwen', submissionComplete: false, results: [
  {id:'queued', status:'queued', productId:'p-1', tags:[], creditRefunded:false},
  {id:'submitting', status:'submitting', productId:'p-1', tags:[], creditRefunded:false},
  {id:'running', status:'loading', taskId:'task-running', productId:'p-1', tags:[], creditRefunded:false}
]}; activeGenerationId = ''; productionFinishBatch('B-STOP');`);
assert.equal(run('state.batch.status'), 'delayed');
assert.equal(run("state.batch.results.find((item) => item.id === 'queued').status"), 'failed');
assert.equal(run("state.batch.results.find((item) => item.id === 'submitting').status"), 'failed');
assert.equal(run("state.batch.results.find((item) => item.id === 'running').status"), 'delayed');
assert.equal(run('state.credits'), 103);
run('sleep = productionSleep; apiJson = productionApiJson;');

run('state = structuredClone(seedState); state.schemaVersion = 7; state.studio.generationMode = "fast"; applySavedState(structuredClone(state));');
assert.equal(run('state.schemaVersion'), 16);
assert.equal(run('state.studio.generationMode'), 'fast');
assert.equal(run('state.savedAssets.every((asset) => asset.demo)'), true);
assert.equal(run('state.promptGroups[0].options.some((option) => option.id === "melbourne")'), true);
assert.equal(run('state.promptGroups.some((group) => group.id === "group-people")'), true);
assert.equal(run('state.promptGroups.find((group) => group.id === "group-people").options.find((option) => option.id === "people-none").selected'), true);
run("state.publicPrompts.push({id: 'white-copy', backgroundMode: 'none', prompt: '纯白背景'}); state.studio.publicPromptId = 'white-copy';");
assert.doesNotMatch(run('generationPrompt(state.products[3], ["当地背景：墨尔本天际线"], [])'), /墨尔本天际线/);
run("regionPreviewId = ''; state.ui.promptDialogGroupId = 'group-location'; state.promptGroups[0].options.find((option) => option.id === 'melbourne').selected = true;");
assert.match(run('renderPromptDialog()'), /添加城市/);
assert.match(run('renderPromptDialog()'), /data-region-prompt/);
assert.match(run('renderPromptDialog()'), /Google Maps Grounding Lite/);
assert.doesNotMatch(run('renderPromptDialog()'), /data-scene-reference|上传截图/);
assert.doesNotMatch(run('renderStudio()'), /id="city-name"/);
assert.doesNotMatch(run('renderStudio()'), /AI 地域背景助手/);
await run("enrichCity('')");
assert.match(run('cityPlannerError'), /请输入/);
run('apiJson = async () => { throw new Error("测试网络错误"); };');
await run("enrichCity('日本·京都')");
assert.equal(run('cityDraft'), '');
assert.match(run('renderPromptDialog()'), /测试网络错误/);
run('apiJson = async () => ({grounding: {summary: "京都木质町屋与庭院景观", sources: [{title: "京都 · Google Maps", url: "https://www.google.com/maps/place/kyoto", placeId: "kyoto"}], resolvedAt: "2026-09-16T00:00:00.000Z", expiresAt: "2099-10-16T00:00:00.000Z"}});');
await run("enrichCity('日本·京都')");
assert.equal(run('state.promptGroups[0].options.filter((option) => option.label === "日本·京都").length'), 1);
assert.equal(run('state.promptGroups[0].options.find((option) => option.id === "melbourne").selected'), true);
assert.equal(run('cityDraft'), '');
assert.match(run('renderPromptDialog()'), /京都木质町屋/);
assert.match(run('renderPromptDialog()'), /查看地图来源/);
const compactStudio = run('renderStudio()');
assert.ok(compactStudio.indexOf('id="studio-provider"') < compactStudio.indexOf('选择参考产品图'));
assert.doesNotMatch(run('renderStudio()'), /id="universal-prompt"|provider-option-grid/);
assert.match(run('generationPrompt(state.products[3], [], [])'), /真实商业摄影质感/);
listeners.change({target: {id: 'studio-provider', value: 'qwen'}});
listeners.change({target: {id: 'studio-quality', value: 'wan'}});
assert.equal(run('state.studio.model'), 'wan2.6-image');
listeners.change({target: {id: 'studio-provider', value: 'openai'}});
assert.equal(run('state.studio.generationMode'), 'quality');
listeners.change({target: {id: 'studio-quality', value: 'fast'}});
assert.equal(run('state.studio.model'), run('PROVIDERS.openai.profiles.fast.code'));
run("state.batch.status = 'generating';");
listeners.change({target: {id: 'studio-provider', value: 'qwen'}});
listeners.change({target: {id: 'studio-quality', value: 'quality'}});
assert.equal(run('state.studio.provider'), 'openai');
assert.equal(run('state.studio.generationMode'), 'fast');
assert.equal((run('renderStudioSettings(true)').match(/disabled/g) || []).length, 2);
run("state.batch.status = 'ready'; state.studio.publicPromptId = 'brief'; comparisonRequested = false; regionPreviewId = ''; preparePromptReview(); state.ui.confirmBatch = true;");
const simplifiedStudio = run('renderStudio()');
assert.doesNotMatch(simplifiedStudio, /id="design-requirements"|公共提示词区|预览首张图的实际提示词/);
assert.ok(simplifiedStudio.indexOf('公共提示词模板') > simplifiedStudio.indexOf('选择提示词组合'));
assert.ok(simplifiedStudio.indexOf('公共提示词模板') < simplifiedStudio.indexOf('class="prompt-group-list"'));
assert.match(run('promptReview.entries[0].prompt'), /Flinders Street Station/);
assert.doesNotMatch(run('generationPrompt(state.products[3], [], [])'), /必须落实的补充要求/);
const clickAction = async (action, data = {}) => { const button = {dataset: {action, ...data}}; await listeners.click({target: {closest: (selector) => selector === '[data-action]' ? button : null}}); };
await clickAction('edit-reviewed-prompt');
assert.equal(run('promptReviewEditing'), true);
listeners.input({target: {id:'final-prompt-text',value:' ' ,dataset:{}}});
await clickAction('save-reviewed-prompt');
assert.equal(run('promptReviewEditing'), true);
assert.match(run('promptReviewError'), /请输入/);
listeners.input({target: {id:'final-prompt-text',value:'修改后的墨尔本地标与帐篷配方',dataset:{}}});
await clickAction('save-reviewed-prompt');
assert.equal(run('promptReviewEditing'), false);
assert.equal(run('reviewedPrompt(selectedProducts()[0], buildCombinations()[0], 0)'), '修改后的墨尔本地标与帐篷配方');
assert.notEqual(run('reviewedPrompt(selectedProducts()[0], buildCombinations()[1], 1)'), '修改后的墨尔本地标与帐篷配方');
run("state.studio.publicPromptId = 'white';");
assert.notEqual(run('reviewedPrompt(selectedProducts()[0], buildCombinations()[0], 0)'), '修改后的墨尔本地标与帐篷配方');
assert.doesNotMatch(run('renderConfirmDialog()'), /Flinders Street Station/);
run("state.studio.provider = 'qwen'; state.studio.generationMode = 'wan'; preparePromptReview(); promptReview.entries[0].prompt = '长'.repeat(2001);");
const creditsBeforeInvalidPrompt = run('state.credits');
run('confirmCurrentPromptReview()');
assert.equal(run('state.credits'), creditsBeforeInvalidPrompt);
assert.equal(run('promptReviewEditing'), true);
assert.match(run('promptReviewError'), /2000.*尚未提交或扣分/);
run("state = structuredClone(seedState); comparisonRequested = false; promptReview = null;");
const finalPromptSection = run('renderFinalPromptSection(false)');
assert.doesNotMatch(finalPromptSection, /小样模型对比|GPT Image|Low 质量|High 质量|张对比图|comparison-context|<dt>参考产品<\/dt>|<dt>首个组合<\/dt>/);
assert.match(finalPromptSection, /悉尼歌剧院/);
assert.match(finalPromptSection, /<h4 id="final-prompt-title">最终提示词<\/h4>/);
assert.match(finalPromptSection, /id="prompt-review-entry"/);
assert.match(finalPromptSection, /id="final-prompt-text"/);
assert.match(finalPromptSection, /data-action="confirm-inline-prompts"/);
assert.doesNotMatch(finalPromptSection, /对比共用提示词|data-action="edit-reviewed-prompt"|<details/);
assert.match(finalPromptSection, /TENT-2P-014/);
assert.equal(run('comparisonRequested'), false);
assert.equal(run('plannedTotal()'), 18);
run("state.studio.provider = 'qwen';");
assert.doesNotMatch(run('renderFinalPromptSection(false)'), /张对比图|Wan 2\.6 Image|data-action="review-comparison"/);
run('state.studio.selectedProductIds = [];');
assert.match(run('renderFinalPromptSection(false)'), /先选择参考产品/);
assert.doesNotMatch(run('renderFinalPromptSection(false)'), /data-action="review-comparison"/);
run('state = structuredClone(seedState); comparisonRequested = false; promptReviewEditing = false; confirmedPromptReviews = {batch: null, comparison: null}; activeGenerationId = "";');
const unconfirmedCredits = run('state.credits');
await run('startBatchGeneration()');
assert.equal(run('state.credits'), unconfirmedCredits);
assert.equal(run('state.batch.results.length'), 0);
assert.match(run('renderStudio()'), /data-action="generate-batch" disabled/);
assert.doesNotMatch(run('renderFinalPromptSection(false)'), /data-action="generate-comparison"/);
assert.doesNotMatch(run('renderStudio()'), /data-action="review-batch"/);
listeners.input({target: {id:'final-prompt-text', value:' ', dataset:{}}});
await clickAction('confirm-inline-prompts');
assert.equal(run('hasConfirmedPromptReview(false)'), false);
assert.match(run('promptReviewError'), /不能为空/);
listeners.input({target: {id:'final-prompt-text', value:'工作台内直接修改的最终提示词', dataset:{}}});
assert.equal(run('promptReview.entries[0].prompt'), '工作台内直接修改的最终提示词');
assert.equal(run('hasConfirmedPromptReview(false)'), false);
await clickAction('confirm-inline-prompts');
assert.equal(run('hasConfirmedPromptReview(false)'), true);
assert.equal(run('state.ui.confirmBatch'), false);
assert.match(run('renderStudio()'), /data-action="generate-batch" >/);
listeners.input({target: {id:'final-prompt-text', value:'再次修改后需要重新确认', dataset:{}}});
assert.equal(run('hasConfirmedPromptReview(false)'), false);
assert.match(run('renderStudio()'), /data-action="generate-batch" disabled/);
run('preparePromptReview(); state.ui.confirmBatch = true;');
assert.match(run('renderConfirmDialog()'), /data-action="confirm-prompts"/);
assert.doesNotMatch(run('renderConfirmDialog()'), /data-action="confirm-batch"|开始生成/);
run('promptReview.entries[0].prompt = "确认过的精修儿童帐篷摄影提示词";');
await clickAction('confirm-prompts');
assert.equal(run('hasConfirmedPromptReview(false)'), true);
assert.equal(run('state.credits'), unconfirmedCredits);
assert.equal(run('state.ui.confirmBatch'), false);
assert.match(run('renderStudio()'), /data-action="generate-batch" >/);
assert.doesNotMatch(run('renderFinalPromptSection(false)'), /data-action="generate-comparison"/);
run('preparePromptReview();');
assert.equal(run('promptReview.entries[0].prompt'), '确认过的精修儿童帐篷摄影提示词');
await clickAction('edit-reviewed-prompt');
assert.equal(run('hasConfirmedPromptReview(false)'), false);
await clickAction('cancel-reviewed-prompt');
await clickAction('confirm-prompts');
for (const mutation of [
  'state.studio.ratio = "1:1";',
  'state.studio.generationMode = "fast";',
  'state.studio.publicPromptId = "white";',
  'state.promptGroups[0].options.find((option) => option.selected).quantity += 1;',
  'state.studio.selectedProductIds = ["p-4"];',
  'state.products[0].name += "修改";'
]) {
  run('state = structuredClone(seedState); comparisonRequested = false; preparePromptReview(); confirmCurrentPromptReview();');
  assert.equal(run('hasConfirmedPromptReview(false)'), true);
  run(mutation);
  assert.equal(run('hasConfirmedPromptReview(false)'), false, mutation);
}
run('state = structuredClone(seedState); preparePromptReview(); confirmCurrentPromptReview(); checkProviderAuthorization = async () => { state.studio.ratio = "1:1"; return true; };');
const creditsBeforeAuthorizationChange = run('state.credits');
await run('startBatchGeneration()');
assert.equal(run('state.credits'), creditsBeforeAuthorizationChange);
assert.equal(run('state.batch.results.length'), 0);
run('checkProviderAuthorization = async () => true; preparePromptReview(); promptReview.entries[0].prompt = "最终确认版本"; confirmCurrentPromptReview(); submitOpenAiBatch = async (results) => { results.forEach((item) => { item.status = "ready"; }); activeGenerationId = ""; state.batch.status = "ready"; };');
await clickAction('generate-batch');
assert.equal(run('state.batch.results.length'), 18);
assert.equal(run('state.batch.results[0].prompt'), '最终确认版本');
assert.equal(run('state.credits'), creditsBeforeAuthorizationChange - 54);
assert.equal(run('hasConfirmedPromptReview(false)'), false);
run('state = structuredClone(seedState); comparisonRequested = false; confirmedPromptReviews = {batch: null, comparison: null};');
assert.equal((run('renderStudio()').match(/class="generation-controls"/g) || []).length, 1);
assert.doesNotMatch(run('renderStudio()'), /生成方式|studio-generation-type|generation-mode-control|data-action="review-comparison"/);
assert.equal(run('plannedTotal()'), 18);
assert.match(run('renderStudio()'), /data-action="generate-batch" disabled/);
run('preparePromptReview(); confirmCurrentPromptReview();');
assert.match(run('renderStudio()'), /data-action="generate-batch" >/);
await clickAction('generate-batch');
assert.equal(run('state.batch.results.length'), 18);
assert.equal(run('state.batch.comparison'), false);
assert.equal(run('state.credits'), run('seedState.credits') - 54);
run('state = structuredClone(seedState); activeGenerationId = ""; state.batch.status = "idle"; comparisonRequested = false;');
const legacyStyles = run(`upgradeVisualStyleGroup({id: 'group-style', name: '视觉风格', enabled: false, options: [
  {id: 'group-style-0', label: '北欧自然', selected: true, quantity: 2},
  {id: 'group-style-1', label: '轻奢柔光', prompt: '保留我手动修改的规则', selected: false, quantity: 1},
  {id: 'my-custom-style', label: '自然晨光', prompt: '我的晨光规则', selected: true, quantity: 1}
]})`);
assert.equal(legacyStyles.enabled, false);
assert.equal(legacyStyles.options.length, 7);
assert.equal(legacyStyles.options[0].id, 'group-style-0');
assert.equal(legacyStyles.options[0].selected, true);
assert.equal(legacyStyles.options[0].quantity, 2);
assert.match(legacyStyles.options[0].prompt, /光线：.*\n色彩：/);
assert.equal(legacyStyles.options[1].prompt, '保留我手动修改的规则');

run('state = structuredClone(seedState);');
await clickAction('use-template', {id: 'tpl-scene'});
assert.equal(run('state.studio.templateId'), 'tpl-scene');
listeners.change({target: {id: 'public-prompt-template', value: 'white', dataset: {}}});
assert.equal(run('state.studio.templateId'), '');
run('state = structuredClone(seedState);');
assert.equal(legacyStyles.options[2].prompt, '我的晨光规则');
run("state.promptGroups.push({id: 'group-style', name: '视觉风格', enabled: true, options: [{id: 'group-style-0', label: '北欧自然', selected: true, quantity: 1}]}); applySavedState(structuredClone(state));");
assert.equal(run('state.promptGroups.find((group) => group.id === "group-style").options.length'), 6);
assert.equal(run('state.promptLibrary.find((group) => group.id === "group-style").options.length'), 6);
for (const style of run('VISUAL_STYLE_OPTIONS')) {
  for (const dimension of ['光线：', '色彩：', '材质：', '构图：', '避免：', '约束：']) assert.ok(style.prompt.includes(dimension), style.label + dimension);
}
run("state.ui.promptDialogGroupId = 'group-style';");
assert.match(run('renderPromptDialog()'), /北欧自然 · 对应提示词/);
assert.match(run('renderPromptDialog()'), /style-rule" open/);
assert.match(run('renderPromptDialog()'), /光线：/);
await clickAction('toggle-prompt-option', {groupId:'group-style', id:'style-dream'});
assert.equal(run('stylePreviewId'), 'style-dream');
assert.match(run('renderPromptDialog()'), /梦幻童趣 · 风格提示词/);
assert.match(run('renderPromptDialog()'), /id="style-prompt-text"/);
const styleCreditsBefore = run('state.credits');
listeners.input({target:{id:'style-prompt-text',value:' ',dataset:{}}});
await clickAction('save-style-prompt');
assert.match(run('stylePromptError'), /1–1600/);
assert.equal(run('stylePreviewId'), 'style-dream');
listeners.input({target:{id:'style-prompt-text',value:'光线：自然晨光。色彩：保持帐篷配色。材质：棉麻纤维。构图：悉尼地标清楚。避免：卡通。',dataset:{}}});
await clickAction('save-style-prompt');
assert.equal(run('stylePreviewId'), '');
assert.equal(run('state.credits'), styleCreditsBefore);
run("state.promptGroups.find((group) => group.id === 'group-style').options.forEach((option) => { option.selected = option.id === 'style-dream'; }); preparePromptReview(); confirmCurrentPromptReview();");
assert.equal(run('hasConfirmedPromptReview(false)'), true);
assert.match(run('promptReview.entries[0].prompt'), /悉尼歌剧院/);
assert.match(run('promptReview.entries[0].prompt'), /光线：自然晨光/);
await clickAction('view-style-prompt', {id:'style-dream'});
listeners.input({target:{id:'style-prompt-text',value:'精修真实摄影，改为柔和侧光，保持产品与地标。',dataset:{}}});
await clickAction('save-style-prompt');
assert.equal(run('hasConfirmedPromptReview(false)'), false);
run("state.studio.publicPromptId = 'white'; preparePromptReview();");
assert.doesNotMatch(run('promptReview.entries[0].prompt'), /悉尼歌剧院/);
assert.match(run('promptReview.entries[0].prompt'), /改为柔和侧光/);
run('applySavedState(structuredClone(state));');
assert.equal(run('state.promptGroups.find((group) => group.id === "group-style").options.find((option) => option.id === "style-dream").prompt'), '精修真实摄影，改为柔和侧光，保持产品与地标。');
run('closeOverlay();');
assert.equal(run('stylePreviewId'), '');
run('state = structuredClone(seedState); state.ui.promptDialogGroupId = "library";');
await clickAction('add-library-group', {id:'group-style'});
assert.equal(run('stylePreviewId'), 'style-nordic');
assert.equal(run('state.promptGroups.find((group) => group.id === "group-style").options.filter((option) => option.selected).length'), 1);
assert.equal(run('plannedTotal()'), 18);
assert.match(run('renderPromptDialog()'), /北欧自然 · 风格提示词/);
await clickAction('back-styles');
assert.match(run('renderPromptDialog()'), /style-rule" open/);
assert.equal(run('state.credits'), run('seedState.credits'));
run('state = structuredClone(seedState); comparisonRequested = false; confirmedPromptReviews = {batch: null, comparison: null};');
const otherUi = run('renderStudio()');
assert.match(otherUi, /label for="studio-other-requirements">其他要求/);
assert.match(otherUi, /aria-describedby="other-requirements-help"/);
assert.ok(otherUi.indexOf('选择提示词组合') < otherUi.indexOf('id="studio-other-requirements"'));
assert.ok(otherUi.indexOf('id="studio-other-requirements"') < otherUi.indexOf('id="final-prompt-title"'));
assert.doesNotMatch(otherUi, /小样模型对比|张对比图|comparison-model-list|comparison-context/);
assert.doesNotMatch(run('generationPrompt(selectedProducts()[0], [], [])'), /其他要求（/);
const otherText = '帐篷上出现小恐龙与星星。孩子在入口旁阅读。不要文字或水印。';
const otherCountBefore = run('plannedTotal()');
const otherCreditsBefore = run('state.credits');
listeners.input({target:{id:'studio-other-requirements',value:otherText,dataset:{}}});
assert.equal(run('state.studio.otherRequirements'), otherText);
assert.equal(run('plannedTotal()'), otherCountBefore);
assert.equal(run('state.credits'), otherCreditsBefore);
run('preparePromptReview();');
for (const entry of run('promptReview.entries')) {
  assert.ok(entry.prompt.includes(otherText));
  assert.match(entry.prompt, /参考产品为|场景任务：|本张创作规则：|产品配色|画幅比例：4:3/);
}
assert.match(run('promptReview.entries[0].prompt'), /悉尼歌剧院/);
run('confirmCurrentPromptReview();');
assert.equal(run('hasConfirmedPromptReview(false)'), true);
listeners.input({target:{id:'studio-other-requirements',value:otherText + ' 产品居中。',dataset:{}}});
assert.equal(run('hasConfirmedPromptReview(false)'), false);
assert.match(run('renderStudio()'), /data-action="generate-batch" disabled/);
run('applySavedState(structuredClone(state)); preparePromptReview();');
assert.equal(run('state.studio.otherRequirements'), otherText + ' 产品居中。');
assert.ok(run('promptReview.entries.every((entry) => entry.prompt.includes(state.studio.otherRequirements))'));
run('confirmCurrentPromptReview();');
await clickAction('generate-batch');
assert.equal(run('state.batch.results.length'), otherCountBefore);
assert.ok(run('state.batch.results.every((item) => item.prompt.includes(state.studio.otherRequirements))'));
assert.equal(run('state.credits'), otherCreditsBefore - otherCountBefore * 3);
listeners.input({target:{id:'studio-other-requirements',value:' ',dataset:{}}});
assert.doesNotMatch(run('generationPrompt(selectedProducts()[0], [], [])'), /其他要求（/);
run('state = structuredClone(seedState); applySavedState({studio: {provider: "openai"}});');
assert.equal(run('state.studio.otherRequirements'), '');
assert.equal(run('state.promptGroups.find((group) => group.id === "group-canvas").options.length'), 5);
assert.deepEqual(run('state.promptGroups.find((group) => group.id === "group-canvas").options.map((option) => option.ratio)'), ['4:3', '16:9', '3:4', '9:16', '1:1']);
assert.deepEqual(run('state.promptGroups.find((group) => group.id === "group-shot").options.map((option) => option.label)'), ['近景', '中景', '远景']);
assert.deepEqual(run('state.promptGroups.find((group) => group.id === "group-shot").options.map((option) => option.description)'), ['帐篷占 80%–95% · 产品细节主导', '帐篷占 45%–60% · 产品环境平衡', '帐篷占 12%–25% · 地域环境主导']);
for (const [shotId, requiredPatterns] of [
  ['shot-close', [/镜头景别硬性约束/, /1–2 米/, /65–85mm/, /80%–95%/, /环境只占 5%–20%/, /不要中景或广角全景/]],
  ['shot-medium', [/镜头景别硬性约束/, /3–5 米/, /45–55mm/, /45%–60%/, /不要近景裁切或远景全景/]],
  ['shot-wide', [/镜头景别硬性约束/, /10–20 米/, /24–35mm/, /12%–25%/, /环境占 75%–88%/, /严禁返回近景或常规中景/]],
]) {
  run("state.promptGroups.find((group) => group.id === 'group-shot').options.forEach((option) => { option.selected = option.id === '" + shotId + "'; });");
  const shotPrompt = run('generationPrompt(selectedProducts()[0], buildCombinations()[0].tags, buildCombinations()[0].promptDetails, buildCombinations()[0].ratio)');
  for (const pattern of requiredPatterns) assert.match(shotPrompt, pattern, shotId + ': ' + pattern);
  assert.match(shotPrompt, /冲突优先级：出现人数与帐篷结构 > 地域场景硬约束 > 镜头景别与画布构图/);
  if (shotId === 'shot-wide') assert.match(shotPrompt, /环境必须主导画面面积，禁止为了突出产品而放大成中景/);
}
assert.match(run('renderPromptGroups()'), /远景 · 帐篷占 12%–25%/);
run("state.ui.promptDialogGroupId = 'group-shot';");
assert.match(run('renderPromptDialog()'), /三种景别按帐篷画面占比严格区分/);
assert.equal(run('plannedTotal()'), 18);
run("state.promptGroups.find((group) => group.id === 'group-canvas').options.forEach((option) => { option.selected = option.id === 'canvas-16-9'; }); state.promptGroups.find((group) => group.id === 'group-shot').options.forEach((option) => { option.selected = option.id === 'shot-wide'; });");
assert.equal(run('plannedTotal()'), 18);
assert.equal(run('buildCombinations()[0].ratio'), '16:9');
assert.match(run('generationPrompt(selectedProducts()[0], buildCombinations()[0].tags, buildCombinations()[0].promptDetails, buildCombinations()[0].ratio)'), /画幅比例：16:9/);
assert.match(run('generationPrompt(selectedProducts()[0], buildCombinations()[0].tags, buildCombinations()[0].promptDetails, buildCombinations()[0].ratio)'), /环境远景或建立镜头/);
run('confirmedPromptReviews = {batch: null, comparison: null}; preparePromptReview(); confirmCurrentPromptReview(); submitOpenAiBatch = async (results) => { results.forEach((item) => { item.status = "ready"; item.image = "data:image/jpeg;base64,aW1hZ2U="; }); activeGenerationId = ""; state.batch.status = "ready"; };');
await run('startBatchGeneration()');
assert.equal(run('new Set(state.batch.results.map((item) => item.ratio)).size'), 1);
assert.equal(run('state.batch.results[0].ratio'), '16:9');
assert.match(run('renderResultGroups()'), /aspect-ratio:16 \/ 9/);
assert.match(run('renderResultGroups()'), /generate-4k-result[\s\S]*download-result[\s\S]*regenerate-result[\s\S]*delete-result/);
const sourceResultId = run('state.batch.results[0].id');
const creditsBefore4K = run('state.credits');
run("upscaleImageTo4K = async () => 'data:image/jpeg;base64,NEs=';");
await run(`generate4KResult(${JSON.stringify(sourceResultId)})`);
assert.equal(run('state.batch.results.length'), 19);
assert.equal(run('state.batch.results[1].is4k'), true);
assert.equal(run('state.batch.results[1].sourceResultId'), sourceResultId);
assert.equal(run('state.batch.results[1].status'), 'ready');
assert.equal(run('state.batch.results[1].image'), 'data:image/jpeg;base64,NEs=');
assert.match(run('state.batch.results[1].tags.join(" ")'), /4K 尺寸 4096×2304/);
assert.equal(run('state.credits'), creditsBefore4K);
await run(`generate4KResult(${JSON.stringify(sourceResultId)})`);
assert.equal(run('state.batch.results.length'), 19);
run("const savedV8 = structuredClone(seedState); savedV8.schemaVersion = 8; savedV8.promptGroups = savedV8.promptGroups.filter((group) => !['group-canvas', 'group-shot'].includes(group.id)); applySavedState(savedV8);");
assert.equal(run('state.schemaVersion'), 16);
assert.equal(run('state.promptGroups.some((group) => group.id === "group-canvas")'), true);
assert.equal(run('state.promptGroups.some((group) => group.id === "group-shot")'), true);
run("const savedV9 = structuredClone(seedState); savedV9.schemaVersion = 9; savedV9.promptGroups.find((group) => group.id === 'group-shot').options.find((option) => option.id === 'shot-wide').prompt = '旧版远景提示词'; applySavedState(savedV9);");
assert.equal(run('state.schemaVersion'), 16);
assert.match(run("state.promptGroups.find((group) => group.id === 'group-shot').options.find((option) => option.id === 'shot-wide').prompt"), /12%–25%/);
run("const savedV10 = structuredClone(seedState); savedV10.schemaVersion = 10; savedV10.promptGroups.find((group) => group.id === 'group-location').options.find((option) => option.id === 'sydney').prompt = '旧版泛化悉尼背景'; applySavedState(savedV10);");
assert.equal(run('state.schemaVersion'), 16);
assert.match(run("state.promptGroups.find((group) => group.id === 'group-location').options.find((option) => option.id === 'sydney').prompt"), /Sydney Opera House/);
run("const savedV11 = structuredClone(seedState); savedV11.schemaVersion = 11; savedV11.publicPrompts.find((template) => template.id === 'family').prompt = '旧版多人玩耍'; savedV11.promptGroups.push({id: 'group-scene', name: '使用场景', enabled: true, options: [{id: 'group-scene-0', label: '儿童房', selected: true, quantity: 1}]}); applySavedState(savedV11);");
assert.equal(run('state.schemaVersion'), 16);
assert.match(run("state.publicPrompts.find((template) => template.id === 'family').prompt"), /人物数量完全服从“出现人数”选项/);
assert.match(run("state.publicPrompts.find((template) => template.id === 'family').prompt"), /每名儿童都必须与帐篷发生/);
assert.match(run("state.promptGroups.find((group) => group.id === 'group-scene').options.find((option) => option.label === '儿童房').prompt"), /同一透视/);
assert.equal(run("state.promptGroups.find((group) => group.id === 'group-scene').options.filter((option) => option.label === '儿童房').length"), 1);
run("const savedV12 = structuredClone(seedState); savedV12.schemaVersion = 12; savedV12.publicPrompts.find((template) => template.id === 'family').prompt = '旧版入口旁摆拍'; applySavedState(savedV12);");
assert.equal(run('state.schemaVersion'), 16);
assert.match(run("state.publicPrompts.find((template) => template.id === 'family').prompt"), /人物数量完全服从“出现人数”选项/);
console.log('Studio canvas sizes, camera shots, 4K queue, other requirements and prompt confirmation tests passed.');
